name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_nfc_kit: ^3.6.0
  encrypt: ^5.0.3
  pointycastle: ^3.4.0
  flutter_launcher_icons: ^0.14.3
  animated_splash_screen: ^1.3.0
  dropdown_search: ^5.0.6
  hive: ^2.2.3 
  hive_flutter: ^1.1.0
  file_picker: ^6.1.1
  path_provider: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logopg_kotak.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logopg_kotak.png"
